# 应用配置
app:
  env: "release"
  debug: false
  port: 8080
  name: "gin-naive-admin-release"

# 数据库配置
database:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  name: "gin-naive-admin"
  charset: "utf8mb4_unicode_ci"
  timezone: "Asia/Shanghai"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600
  log-mode: ""
  log-zap: false
  # 连接池配置
  pool:
    min_idle: 2
    max_retries: 3
    idle_timeout: 300