// Code generated by devform — 请根据业务再核对字段与校验标签。
package [[.PackageName]]

import (
	"gin-admin-server/global"
	"gin-admin-server/model/page_info"
[[if .HasTimeType -]]
	"gin-admin-server/utils/time_util"
[[end]]
)

// [[.EntityName]] 由在线表单生成
type [[.EntityName]] struct {
	global.GNA_MODEL
[[range .Fields -]]
	[[.GoName]] [[.GoType]] `[[.StructTags]]`
[[end]]
}

func ([[.EntityName]]) TableName() string {
	return "[[.TableName]]"
}

// [[.EntityName]]ListFilters 列表筛选（由可查询字段生成）
type [[.EntityName]]ListFilters struct {
[[range .QueryFields -]]
	[[.GoName]] [[.GoType]] `form:"[[.JSONName]]"`
[[end]]
}

// [[.EntityName]]PageRequest 分页请求
type [[.EntityName]]PageRequest struct {
	page_info.PageInfo
	[[.EntityName]]ListFilters
}
