// Code generated by devform
package [[.PackageName]]

import "github.com/gin-gonic/gin"

type _[[.ServiceVar]]Router struct{}

var [[.EntityName]]Router = new(_[[.ServiceVar]]Router)

func (r *_[[.ServiceVar]]Router) Init[[.EntityName]]Router(Router *gin.RouterGroup) {
	g := Router.Group("[[.RouteGroup]]")
	{
		g.GET("list", [[.EntityName]]Service.Get[[.EntityName]]List)
		g.GET("query/:id", [[.EntityName]]Service.Query[[.EntityName]])
		g.POST("add", [[.EntityName]]Service.Add[[.EntityName]])
		g.PUT("edit", [[.EntityName]]Service.Edit[[.EntityName]])
		g.DELETE("delete/:id", [[.EntityName]]Service.Delete[[.EntityName]])
	}
}
