// Code generated by devform
package [[.PackageName]]

import (
	"gin-admin-server/global"
	"gin-admin-server/model/response"
	"gin-admin-server/utils/dbctx"
	"gin-admin-server/utils/validator"

	"github.com/gin-gonic/gin"
)

type _[[.ServiceVar]]Service struct{}

var [[.EntityName]]Service = new(_[[.ServiceVar]]Service)

func (s *_[[.ServiceVar]]Service) Get[[.EntityName]]List(c *gin.Context) {
	var list [][[.EntityName]]
	var req [[.EntityName]]PageRequest
	if err := c.ShouldBindQuery(&req); err != nil {
		response.FailWithMessage(validator.GetValidatorErrorMessage(err, req), c)
		return
	}
	db := dbctx.Use(c).Model(&[[.EntityName]]{})
[[range .QueryBlocks -]]
	[[.]]
[[end]]
	var total int64
	if err := db.Count(&total).Error; err != nil {
		response.FailWithMessage("查询失败", c)
		return
	}
	limit := req.PageSize
	offset := req.PageSize * (req.PageNo - 1)
	if err := db.Limit(limit).Offset(offset).Order("id DESC").Find(&list).Error; err != nil {
		response.FailWithMessage("查询失败", c)
		return
	}
	global.FillAuditDisplayNames(dbctx.Use(c), &list)
	response.OkWithData(response.PageResult{List: list, Total: total, PageNo: req.PageNo, PageSize: req.PageSize}, c)
}

func (s *_[[.ServiceVar]]Service) Query[[.EntityName]](c *gin.Context) {
	id := c.Param("id")
	if id == "" {
		response.FailWithMessage("id 不能为空", c)
		return
	}
	var row [[.EntityName]]
	if err := dbctx.Use(c).Where("id = ?", id).First(&row).Error; err != nil {
		response.FailWithMessage("记录不存在", c)
		return
	}
	global.FillAuditDisplayNames(dbctx.Use(c), &row)
	response.OkWithData(row, c)
}

func (s *_[[.ServiceVar]]Service) Add[[.EntityName]](c *gin.Context) {
	var row [[.EntityName]]
	if err := c.ShouldBindJSON(&row); err != nil {
		response.FailWithMessage(validator.GetValidatorErrorMessage(err, row), c)
		return
	}
	row.ID = 0
	if err := dbctx.Use(c).Create(&row).Error; err != nil {
		response.FailWithMessage("新增失败", c)
		return
	}
	response.Ok(c)
}

func (s *_[[.ServiceVar]]Service) Edit[[.EntityName]](c *gin.Context) {
	var row [[.EntityName]]
	if err := c.ShouldBindJSON(&row); err != nil {
		response.FailWithMessage(validator.GetValidatorErrorMessage(err, row), c)
		return
	}
	if row.ID == 0 {
		response.FailWithMessage("id 不能为空", c)
		return
	}
	if err := dbctx.Use(c).Save(&row).Error; err != nil {
		response.FailWithMessage("修改失败", c)
		return
	}
	response.Ok(c)
}

func (s *_[[.ServiceVar]]Service) Delete[[.EntityName]](c *gin.Context) {
	id := c.Param("id")
	if id == "" {
		response.FailWithMessage("id 不能为空", c)
		return
	}
	if err := dbctx.Use(c).Where("id = ?", id).Delete(&[[.EntityName]]{}).Error; err != nil {
		response.FailWithMessage("删除失败", c)
		return
	}
	response.Ok(c)
}
