// Code generated by devform — 请根据业务再核对字段与校验标签。
package demo_dict

import (
	"gin-admin-server/global"
	"gin-admin-server/model/page_info"

)

// DemoDict 由在线表单生成
type DemoDict struct {
	global.GNA_MODEL
DemoDictCode string `gorm:"column:demo_dict_code;type:varchar(100);not null;comment:测试代码生成字典编码" json:"demoDictCode" binding:"required"`
DemoDictName string `gorm:"column:demo_dict_name;type:varchar(100);not null;comment:测试代码生成-字典名称" json:"demoDictName" binding:"required"`

}

func (DemoDict) TableName() string {
	return "demo_dict"
}

// DemoDictListFilters 列表筛选（由可查询字段生成）
type DemoDictListFilters struct {
DemoDictCode string `form:"demoDictCode"`
DemoDictName string `form:"demoDictName"`

}

// DemoDictPageRequest 分页请求
type DemoDictPageRequest struct {
	page_info.PageInfo
	DemoDictListFilters
}
