// Code generated by devform
package demo_dict

import "github.com/gin-gonic/gin"

type _demoDictRouter struct{}

var DemoDictRouter = new(_demoDictRouter)

func (r *_demoDictRouter) InitDemoDictRouter(Router *gin.RouterGroup) {
	g := Router.Group("demo_dict")
	{
		g.GET("list", DemoDictService.GetDemoDictList)
		g.GET("query/:id", DemoDictService.QueryDemoDict)
		g.POST("add", DemoDictService.AddDemoDict)
		g.PUT("edit", DemoDictService.EditDemoDict)
		g.DELETE("delete/:id", DemoDictService.DeleteDemoDict)
	}
}
