// Code generated by devform
package demo_dict

import (
	"gin-admin-server/global"
	"gin-admin-server/model/response"
	"gin-admin-server/utils/dbctx"
	"gin-admin-server/utils/validator"

	"github.com/gin-gonic/gin"
)

type _demoDictService struct{}

var DemoDictService = new(_demoDictService)

func (s *_demoDictService) GetDemoDictList(c *gin.Context) {
	var list []DemoDict
	var req DemoDictPageRequest
	if err := c.ShouldBindQuery(&req); err != nil {
		response.FailWithMessage(validator.GetValidatorErrorMessage(err, req), c)
		return
	}
	db := dbctx.Use(c).Model(&DemoDict{})
	if req.DemoDictCode != "" {
		db = db.Where("`demo_dict_code` = ?", req.DemoDictCode)
	}

	if req.DemoDictName != "" {
		db = db.Where("`demo_dict_name` LIKE ?", "%"+req.DemoDictName+"%")
	}


	var total int64
	if err := db.Count(&total).Error; err != nil {
		response.FailWithMessage("查询失败", c)
		return
	}
	limit := req.PageSize
	offset := req.PageSize * (req.PageNo - 1)
	if err := db.Limit(limit).Offset(offset).Order("id DESC").Find(&list).Error; err != nil {
		response.FailWithMessage("查询失败", c)
		return
	}
	global.FillAuditDisplayNames(dbctx.Use(c), &list)
	response.OkWithData(response.PageResult{List: list, Total: total, PageNo: req.PageNo, PageSize: req.PageSize}, c)
}

func (s *_demoDictService) QueryDemoDict(c *gin.Context) {
	id := c.Param("id")
	if id == "" {
		response.FailWithMessage("id 不能为空", c)
		return
	}
	var row DemoDict
	if err := dbctx.Use(c).Where("id = ?", id).First(&row).Error; err != nil {
		response.FailWithMessage("记录不存在", c)
		return
	}
	global.FillAuditDisplayNames(dbctx.Use(c), &row)
	response.OkWithData(row, c)
}

func (s *_demoDictService) AddDemoDict(c *gin.Context) {
	var row DemoDict
	if err := c.ShouldBindJSON(&row); err != nil {
		response.FailWithMessage(validator.GetValidatorErrorMessage(err, row), c)
		return
	}
	row.ID = 0
	if err := dbctx.Use(c).Create(&row).Error; err != nil {
		response.FailWithMessage("新增失败", c)
		return
	}
	response.Ok(c)
}

func (s *_demoDictService) EditDemoDict(c *gin.Context) {
	var row DemoDict
	if err := c.ShouldBindJSON(&row); err != nil {
		response.FailWithMessage(validator.GetValidatorErrorMessage(err, row), c)
		return
	}
	if row.ID == 0 {
		response.FailWithMessage("id 不能为空", c)
		return
	}
	if err := dbctx.Use(c).Save(&row).Error; err != nil {
		response.FailWithMessage("修改失败", c)
		return
	}
	response.Ok(c)
}

func (s *_demoDictService) DeleteDemoDict(c *gin.Context) {
	id := c.Param("id")
	if id == "" {
		response.FailWithMessage("id 不能为空", c)
		return
	}
	if err := dbctx.Use(c).Where("id = ?", id).Delete(&DemoDict{}).Error; err != nil {
		response.FailWithMessage("删除失败", c)
		return
	}
	response.Ok(c)
}
